spellername = "Baniwa"
spellerversion = "0.1.0"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Baniwa spellchecker"
bwi = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Baniwa, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
bwi = "TRANSLATE: A spellchecker for Baniwa, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.bwi"

[windows]
system_product_code = "{REPLACE_WITH_REAL_SYSTEM_PROD_CODE}_is1"
