template = "https://github.com/giellalt/template-lang-und"
rev_id = 307
template_sha = "6f7d35fea20007282cb2085308400ab4050d8be7"

[replacements]
__GLOTTOLOG_ID__ = "bani1255"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-bwi"
__UND2C__ = "bwi"
__UNDEFINED__ = "Baniwa"
__UND__ = "bwi"
