template = "https://github.com/giellalt/template-lang-und"
rev_id = 298
template_sha = "4822abccfb9b3ce82bf2876217cde02b5f647d14"

[replacements]
__GLOTTOLOG_ID__ = "bani1255"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-bwi"
__UND2C__ = "bwi"
__UNDEFINED__ = "Baniwa"
__UND__ = "bwi"
