template = "https://github.com/giellalt/template-lang-und"
rev_id = 280
template_sha = "6beee360d8349c39749ac477719ead241493924c"

[replacements]
__GLOTTOLOG_ID__ = "bani1255"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-bwi"
__UND2C__ = "bwi"
__UNDEFINED__ = "Baniwa"
__UND__ = "bwi"
